Fix doctrine type mapping and sql declaration
lamoda/php-enum-bundle pull request #1
Opened 2019-05-20 07:59 UTC by dedpikhto

2019-05-20 10:47 UTC, scaytrase requested changes

2019-05-20 10:47 UTC, scaytrase commented on src/DBAL/EnumType.php
> +        return $this->name;
This change will break everything if there is no type alias present in database for this type

2019-08-01 15:33 UTC, dedpikhto commented
Review, please

2019-08-01 18:05 UTC, scaytrase requested changes
Some minor comments. All other looks good

2019-08-01 18:05 UTC, scaytrase commented on src/DependencyInjection/LamodaEnumExtension.php
> +            $enumNameTypeMapping = false;
we can use `??` here

2019-08-01 18:05 UTC, scaytrase commented on src/DependencyInjection/Configuration.php
> +        $root->children()->scalarNode('enum_name_type_mapping')
`booleanNode`

2019-08-01 19:22 UTC, dedpikhto commented on src/DependencyInjection/LamodaEnumExtension.php
> +            $enumNameTypeMapping = false;
Already removed at all

2019-08-01 19:22 UTC, dedpikhto commented on src/DependencyInjection/Configuration.php
> +        $root->children()->scalarNode('enum_name_type_mapping')
fixed

2019-08-02 06:57 UTC, merged

2019-08-02 06:58 UTC, scaytrase commented
Thank you, @dedpikhto